package model.hibernate;

// Generated 23/09/2013 21:12:48 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Leito generated by hbm2java
 */
@Entity
@Table(name = "leito", catalog = "sghh")
public class Leito implements java.io.Serializable {

	private Integer leitoId;
	private Quarto quarto;
	private String identificacao;
	private byte status;
	private Set<Ocupacao> ocupacaos = new HashSet<Ocupacao>(0);

	public Leito() {
	}

	public Leito(Quarto quarto, String identificacao, byte status) {
		this.quarto = quarto;
		this.identificacao = identificacao;
		this.status = status;
	}

	public Leito(Quarto quarto, String identificacao, byte status,
			Set<Ocupacao> ocupacaos) {
		this.quarto = quarto;
		this.identificacao = identificacao;
		this.status = status;
		this.ocupacaos = ocupacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LeitoId", unique = true, nullable = false)
	public Integer getLeitoId() {
		return this.leitoId;
	}

	public void setLeitoId(Integer leitoId) {
		this.leitoId = leitoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QuartoId", nullable = false)
	public Quarto getQuarto() {
		return this.quarto;
	}

	public void setQuarto(Quarto quarto) {
		this.quarto = quarto;
	}

	@Column(name = "Identificacao", nullable = false, length = 10)
	public String getIdentificacao() {
		return this.identificacao;
	}

	public void setIdentificacao(String identificacao) {
		this.identificacao = identificacao;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leito")
	public Set<Ocupacao> getOcupacaos() {
		return this.ocupacaos;
	}

	public void setOcupacaos(Set<Ocupacao> ocupacaos) {
		this.ocupacaos = ocupacaos;
	}

}
