package model.hibernate;

// Generated 23/09/2013 21:12:48 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ocupacao generated by hbm2java
 */
@Entity
@Table(name = "ocupacao", catalog = "sghh")
public class Ocupacao implements java.io.Serializable {

	private Integer ocupacaoId;
	private Leito leito;
	private Funcionario funcionarioByFuncCadastro;
	private Funcionario funcionarioByFuncBaixa;
	private Paciente paciente;
	private String laudo;
	private Date dataCad;
	private Date horaCad;
	private Date dataBaixa;
	private Date horaBaixa;

	public Ocupacao() {
	}

	public Ocupacao(Leito leito, Funcionario funcionarioByFuncCadastro,
			Paciente paciente, Date dataCad, Date horaCad) {
		this.leito = leito;
		this.funcionarioByFuncCadastro = funcionarioByFuncCadastro;
		this.paciente = paciente;
		this.dataCad = dataCad;
		this.horaCad = horaCad;
	}

	public Ocupacao(Leito leito, Funcionario funcionarioByFuncCadastro,
			Funcionario funcionarioByFuncBaixa, Paciente paciente,
			String laudo, Date dataCad, Date horaCad, Date dataBaixa,
			Date horaBaixa) {
		this.leito = leito;
		this.funcionarioByFuncCadastro = funcionarioByFuncCadastro;
		this.funcionarioByFuncBaixa = funcionarioByFuncBaixa;
		this.paciente = paciente;
		this.laudo = laudo;
		this.dataCad = dataCad;
		this.horaCad = horaCad;
		this.dataBaixa = dataBaixa;
		this.horaBaixa = horaBaixa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OcupacaoId", unique = true, nullable = false)
	public Integer getOcupacaoId() {
		return this.ocupacaoId;
	}

	public void setOcupacaoId(Integer ocupacaoId) {
		this.ocupacaoId = ocupacaoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LeitoId", nullable = false)
	public Leito getLeito() {
		return this.leito;
	}

	public void setLeito(Leito leito) {
		this.leito = leito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FuncCadastro", nullable = false)
	public Funcionario getFuncionarioByFuncCadastro() {
		return this.funcionarioByFuncCadastro;
	}

	public void setFuncionarioByFuncCadastro(
			Funcionario funcionarioByFuncCadastro) {
		this.funcionarioByFuncCadastro = funcionarioByFuncCadastro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FuncBaixa")
	public Funcionario getFuncionarioByFuncBaixa() {
		return this.funcionarioByFuncBaixa;
	}

	public void setFuncionarioByFuncBaixa(Funcionario funcionarioByFuncBaixa) {
		this.funcionarioByFuncBaixa = funcionarioByFuncBaixa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PacienteId", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@Column(name = "Laudo", length = 65535)
	public String getLaudo() {
		return this.laudo;
	}

	public void setLaudo(String laudo) {
		this.laudo = laudo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DataCad", nullable = false, length = 10)
	public Date getDataCad() {
		return this.dataCad;
	}

	public void setDataCad(Date dataCad) {
		this.dataCad = dataCad;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HoraCad", nullable = false, length = 8)
	public Date getHoraCad() {
		return this.horaCad;
	}

	public void setHoraCad(Date horaCad) {
		this.horaCad = horaCad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DataBaixa", length = 10)
	public Date getDataBaixa() {
		return this.dataBaixa;
	}

	public void setDataBaixa(Date dataBaixa) {
		this.dataBaixa = dataBaixa;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HoraBaixa", length = 8)
	public Date getHoraBaixa() {
		return this.horaBaixa;
	}

	public void setHoraBaixa(Date horaBaixa) {
		this.horaBaixa = horaBaixa;
	}

}
