package model.hibernate;

// Generated 23/09/2013 21:12:48 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", catalog = "sghh", uniqueConstraints = @UniqueConstraint(columnNames = "Cpf"))
public class Paciente implements java.io.Serializable {

	private Integer pacienteId;
	private String nome;
	private byte sexo;
	private String cpf;
	private String logradouro;
	private String numero;
	private String complemento;
	private String bairro;
	private String cidade;
	private String estado;
	private byte tipo;
	private byte status;
	private Date dataHora;
	private Set<Ocupacao> ocupacaos = new HashSet<Ocupacao>(0);
	private Set<Telefone> telefones = new HashSet<Telefone>(0);

	public Paciente() {
	}

	public Paciente(String nome, byte sexo, String cpf, byte tipo, byte status,
			Date dataHora) {
		this.nome = nome;
		this.sexo = sexo;
		this.cpf = cpf;
		this.tipo = tipo;
		this.status = status;
		this.dataHora = dataHora;
	}

	public Paciente(String nome, byte sexo, String cpf, String logradouro,
			String numero, String complemento, String bairro, String cidade,
			String estado, byte tipo, byte status, Date dataHora,
			Set<Ocupacao> ocupacaos, Set<Telefone> telefones) {
		this.nome = nome;
		this.sexo = sexo;
		this.cpf = cpf;
		this.logradouro = logradouro;
		this.numero = numero;
		this.complemento = complemento;
		this.bairro = bairro;
		this.cidade = cidade;
		this.estado = estado;
		this.tipo = tipo;
		this.status = status;
		this.dataHora = dataHora;
		this.ocupacaos = ocupacaos;
		this.telefones = telefones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PacienteId", unique = true, nullable = false)
	public Integer getPacienteId() {
		return this.pacienteId;
	}

	public void setPacienteId(Integer pacienteId) {
		this.pacienteId = pacienteId;
	}

	@Column(name = "Nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "Sexo", nullable = false)
	public byte getSexo() {
		return this.sexo;
	}

	public void setSexo(byte sexo) {
		this.sexo = sexo;
	}

	@Column(name = "Cpf", unique = true, nullable = false, length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "Logradouro", length = 50)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "Numero", length = 10)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "Complemento", length = 10)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "Bairro", length = 40)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "Cidade", length = 40)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "Estado", length = 2)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "Tipo", nullable = false)
	public byte getTipo() {
		return this.tipo;
	}

	public void setTipo(byte tipo) {
		this.tipo = tipo;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataHora", nullable = false, length = 19)
	public Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente")
	public Set<Ocupacao> getOcupacaos() {
		return this.ocupacaos;
	}

	public void setOcupacaos(Set<Ocupacao> ocupacaos) {
		this.ocupacaos = ocupacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente")
	public Set<Telefone> getTelefones() {
		return this.telefones;
	}

	public void setTelefones(Set<Telefone> telefones) {
		this.telefones = telefones;
	}

}
