package model.hibernate;

// Generated 23/09/2013 21:12:48 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quarto generated by hbm2java
 */
@Entity
@Table(name = "quarto", catalog = "sghh")
public class Quarto implements java.io.Serializable {

	private Integer quartoId;
	private String andar;
	private String identificacao;
	private byte status;
	private Set<Leito> leitos = new HashSet<Leito>(0);

	public Quarto() {
	}

	public Quarto(String andar, String identificacao, byte status) {
		this.andar = andar;
		this.identificacao = identificacao;
		this.status = status;
	}

	public Quarto(String andar, String identificacao, byte status,
			Set<Leito> leitos) {
		this.andar = andar;
		this.identificacao = identificacao;
		this.status = status;
		this.leitos = leitos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QuartoId", unique = true, nullable = false)
	public Integer getQuartoId() {
		return this.quartoId;
	}

	public void setQuartoId(Integer quartoId) {
		this.quartoId = quartoId;
	}

	@Column(name = "Andar", nullable = false, length = 10)
	public String getAndar() {
		return this.andar;
	}

	public void setAndar(String andar) {
		this.andar = andar;
	}

	@Column(name = "Identificacao", nullable = false, length = 10)
	public String getIdentificacao() {
		return this.identificacao;
	}

	public void setIdentificacao(String identificacao) {
		this.identificacao = identificacao;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quarto")
	public Set<Leito> getLeitos() {
		return this.leitos;
	}

	public void setLeitos(Set<Leito> leitos) {
		this.leitos = leitos;
	}

}
