package model.hibernate;

// Generated 23/09/2013 21:12:48 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefone generated by hbm2java
 */
@Entity
@Table(name = "telefone", catalog = "sghh")
public class Telefone implements java.io.Serializable {

	private Integer telefoneId;
	private Paciente paciente;
	private String telefone;

	public Telefone() {
	}

	public Telefone(Paciente paciente, String telefone) {
		this.paciente = paciente;
		this.telefone = telefone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TelefoneId", unique = true, nullable = false)
	public Integer getTelefoneId() {
		return this.telefoneId;
	}

	public void setTelefoneId(Integer telefoneId) {
		this.telefoneId = telefoneId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PacienteId", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@Column(name = "Telefone", nullable = false, length = 14)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

}
